<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="GHIElectronics.TinyCLR.Drivers.Microchip.Winc15x0">
      <HintPath>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Drivers.Microchip.Winc15x0.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <_Winc15x0ImplSource>$(MSBuildThisFileDirectory)..\..\lib\net48\GHIElectronics.TinyCLR.Drivers.Microchip.Winc15x0.dll</_Winc15x0ImplSource>
  </PropertyGroup>
  <Target Name="CopyWinc15x0ImplForDebugger" AfterTargets="AfterBuild" Condition="Exists('$(_Winc15x0ImplSource)')">
    <Copy SourceFiles="$(_Winc15x0ImplSource)" DestinationFiles="$(OutDir)pe\GHIElectronics.TinyCLR.Drivers.Microchip.Winc15x0.dll" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="false" />
  </Target>
</Project>
